"""empty message

Revision ID: 4414577472b3
Revises: 5018bd1800cc
Create Date: 2023-10-19 02:40:55.956824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4414577472b3'
down_revision = '5018bd1800cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('offer',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.alter_column('offer',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
